keywords:
  high_priority:
    - gravitational wave
    - black hole
    - neutron star
    - LIGO
    - merger
    - gravitational lensing
  
  medium_priority:
    - cosmology
    - dark matter
    - dark energy
    - relativity
    - spacetime
    - Einstein
    - metric
    - curvature
  
  low_priority:
    - numerical
    - simulation

arxiv_categories:
  - gr-qc
  - astro-ph.CO

days_lookback: 7  # Back to 7 now that holidays are over
max_articles: 20
top_n: 5
